	<?php
		//basename($PHP_SELF)="login.php";
		
	?>
	

	<style type="text/css">
<!--
.style1 {color: #FFFFFF}
-->
    </style>
	
	<table align="center" border="0" cellpadding="0" cellspacing="0" width="700">
		<tr>
			<td><hr></td>
		</tr>
		<tr>
			<td width=10></td>
		</tr>
		<tr>
			<td align="center" class="BlackSmlNormal style1">2009 &copy; All Rights Reserved by Cinemax.com.</td>
		</tr>
	</table>
<?php mysql_close(); ?>
</body>
</html>
